version: '2'
services:
    abc-app:
        image: abc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://abc-mysql:3306/abc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    abc-mysql:
        extends:
            file: mysql.yml
            service: abc-mysql
